#!/usr/bin/env bash
# shellcheck disable=SC2154
set -Eeuo pipefail

readonly APP_DIR='/opt/alexandrie'
readonly CONFIG_DIR='/etc/alexandrie'
readonly LIB_DIR='/usr/local/lib/alexandrie'
readonly BIN_DIR='/usr/local/sbin'
readonly ASSET_BASE_URL="${ALEXANDRIE_ASSET_BASE_URL:-}"
readonly INSTALLER_VERSION="${ALEXANDRIE_RELEASE_VERSION:-unreleased}"

phase='initialization'

on_error() {
    printf '[ERROR] Installation fehlgeschlagen (Phase: %s, Zeile: %s).\n' "$phase" "$1" >&2
    printf '[INFO] Für die Diagnose bleiben vorhandene Dateien und Container erhalten.\n' >&2
    exit 1
}
trap 'on_error "$LINENO"' ERR

require_root() {
    [[ ${EUID:-$(id -u)} -eq 0 ]] || { printf '[ERROR] Als root ausführen.\n' >&2; exit 1; }
}

fail_if_existing_installation() {
    if [[ -e $APP_DIR/.env || -e $APP_DIR/compose.yaml || -e $APP_DIR/.installed ]]; then
        printf '[ERROR] Alexandrie ist bereits eingerichtet: %s\n' "$APP_DIR" >&2
        printf '[INFO] Verwende alexandrie-update oder alexandrie-config.\n' >&2
        exit 1
    fi
}

check_network() {
    local url
    for url in \
        'https://deb.debian.org' \
        'https://download.docker.com' \
        'https://ghcr.io' \
        "${ASSET_BASE_URL:-https://raw.githubusercontent.com}"; do
        curl --fail --silent --show-error --location --connect-timeout 10 --max-time 30 \
            -o /dev/null "$url" || {
                printf '[ERROR] HTTPS-Zugriff nicht möglich: %s\n' "$url" >&2
                exit 1
            }
    done
}

install_docker() {
    local architecture codename keyring repo_file
    architecture=$(dpkg --print-architecture)
    [[ $architecture == amd64 ]] || { printf '[ERROR] Nur amd64 ist freigegeben.\n' >&2; exit 1; }
    # shellcheck disable=SC1091
    source /etc/os-release
    codename=${VERSION_CODENAME:-trixie}
    [[ $codename == trixie ]] || { printf '[ERROR] Debian 13 (trixie) wird erwartet.\n' >&2; exit 1; }

    install -d -o root -g root -m 0755 /etc/apt/keyrings
    keyring='/etc/apt/keyrings/docker.asc'
    curl --fail --silent --show-error --location \
        https://download.docker.com/linux/debian/gpg -o "$keyring"
    chmod 0644 "$keyring"
    repo_file='/etc/apt/sources.list.d/docker.list'
    printf 'deb [arch=%s signed-by=%s] https://download.docker.com/linux/debian %s stable\n' \
        "$architecture" "$keyring" "$codename" > "$repo_file"
    apt-get update
    apt-get install --yes docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    systemctl enable --now docker
    docker info >/dev/null
    docker compose version
}

download_assets() {
    local asset target tmp
    [[ -n $ASSET_BASE_URL ]] || {
        printf '[ERROR] ALEXANDRIE_ASSET_BASE_URL fehlt.\n' >&2
        exit 1
    }
    [[ $ASSET_BASE_URL == https://* ]] || {
        printf '[ERROR] Asset-Quelle muss HTTPS verwenden.\n' >&2
        exit 1
    }
    install -d -o root -g root -m 0755 "$APP_DIR" "$APP_DIR/backups" "$CONFIG_DIR" "$LIB_DIR"
    tmp=$(mktemp -d)
    for asset in \
        compose.yaml \
        lib.sh \
        alexandrie-config \
        alexandrie-update \
        alexandrie-backup \
        alexandrie-restore \
        alexandrie-admin \
        alexandrie-health \
        alexandrie.service; do
        target="$tmp/$asset"
        curl --fail --silent --show-error --location --connect-timeout 15 --max-time 60 \
            "$ASSET_BASE_URL/assets/alexandrie/$asset" -o "$target"
    done

    install -o root -g root -m 0644 "$tmp/compose.yaml" "$APP_DIR/compose.yaml"
    install -o root -g root -m 0644 "$tmp/lib.sh" "$LIB_DIR/lib.sh"
    for asset in alexandrie-config alexandrie-update alexandrie-backup alexandrie-restore alexandrie-admin alexandrie-health; do
        install -o root -g root -m 0755 "$tmp/$asset" "$BIN_DIR/$asset"
    done
    install -o root -g root -m 0644 "$tmp/alexandrie.service" /etc/systemd/system/alexandrie.service
    rm -rf -- "$tmp"
}

write_initial_environment() {
    local environment_file tmp
    environment_file="$APP_DIR/.env"
    tmp=$(mktemp "${environment_file}.XXXXXX")
    chmod 600 "$tmp"
    cat > "$tmp" <<'EOF'
# Generated by the Alexandrie Proxmox LXC installer. Keep mode 0600.
FRONTEND_URL=""
API_URL=""
CDN_URL=""
CDN_ENDPOINT="/alexandrie/"
MINIO_PUBLIC_URL=""
COOKIE_DOMAIN=""
ALLOW_UNSECURE="false"
CONFIG_DISABLE_LANDING="false"
CONFIG_DISABLE_SIGNUP="false"
CONFIG_DISABLE_NATIVE_LOGIN="false"
CONFIG_HIDE_NATIVE_LOGIN="false"
CONFIG_HIDE_NATIVE_LOGIN_FORM="false"
CONFIG_OIDC_PROVIDER_AUTO_REDIRECT=""
ADMIN_ACCOUNTS=""

MYSQL_IMAGE="mysql:8.0"
MYSQL_DATABASE="alexandrie"
MYSQL_USER="alexandrie"
MYSQL_PASSWORD=""
MYSQL_ROOT_PASSWORD=""

RUSTFS_IMAGE="rustfs/rustfs:latest"
RUSTFS_ACCESS_KEY=""
RUSTFS_SECRET_KEY=""
RUSTFS_CONSOLE_ENABLE="false"
RUSTFS_LOG_LEVEL="info"
MINIO_BUCKET="alexandrie"
MINIO_SECURE="false"
MINIO_INSECURE_TLS="false"

ALEXANDRIE_BACKEND_IMAGE="ghcr.io/smaug6739/alexandrie-backend:latest"
ALEXANDRIE_FRONTEND_IMAGE="ghcr.io/smaug6739/alexandrie-frontend:latest"

FRONTEND_BIND="0.0.0.0"
BACKEND_BIND="0.0.0.0"
RUSTFS_BIND="0.0.0.0"
SMTP_HOST=""
SMTP_MAIL=""
SMTP_MAIL_FROM=""
SMTP_PASSWORD=""
OIDC_1_CONFIG_URL=""
OIDC_1_CLIENT_ID=""
OIDC_1_CLIENT_SECRET=""
OIDC_1_PROVIDER_NAME="Authentik"
OIDC_CA_SOURCE=""
BACKUP_RETENTION="7"
EOF
    mv -f -- "$tmp" "$environment_file"
    chown root:root "$environment_file"
    chmod 600 "$environment_file"

    # shellcheck disable=SC1091
    source "$LIB_DIR/lib.sh"
    set_env_value JWT_SECRET "$(openssl rand -hex 32)"
    set_env_value ALEXANDRIE_INSTALLER_RELEASE "$INSTALLER_VERSION"
    set_env_value MYSQL_PASSWORD "$(openssl rand -hex 24)"
    set_env_value MYSQL_ROOT_PASSWORD "$(openssl rand -hex 24)"
    set_env_value RUSTFS_ACCESS_KEY "alexandrie-$(openssl rand -hex 12)"
    set_env_value RUSTFS_SECRET_KEY "$(openssl rand -hex 32)"
    install -o root -g root -m 0644 /etc/ssl/certs/ca-certificates.crt "$CONFIG_DIR/oidc-ca-bundle.pem"
}

wait_for_stack() {
    local deadline now status
    deadline=$((SECONDS + 180))
    while (( SECONDS < deadline )); do
        status=$(docker compose --project-name alexandrie --env-file "$APP_DIR/.env" \
            --file "$APP_DIR/compose.yaml" ps --format '{{.Name}}={{.State}}={{.Health}}' 2>/dev/null || true)
        printf '%s\n' "$status" | sed 's/[[:space:]]*$//' | head -n 8
        if \
            wait_http 'http://127.0.0.1:8200/' 2>/dev/null && \
            wait_http 'http://127.0.0.1:8201/api/auth/oidc/providers' 2>/dev/null && \
            wait_http 'http://127.0.0.1:9000/health/ready' 2>/dev/null; then
            return 0
        fi
        sleep 5
    done
    return 1
}

wait_http() {
    local url=$1 timeout=${2:-10} start
    start=$SECONDS
    while (( SECONDS - start < timeout )); do
        local code
        code=$(curl --silent --output /dev/null --write-out '%{http_code}' \
            --connect-timeout 2 --max-time 5 "$url" || true)
        [[ $code =~ ^[23][0-9][0-9]$ ]] && return 0
        sleep 1
    done
    return 1
}

print_summary() {
    local ip frontend api cdn
    ALEXANDRIE_APP_DIR=$APP_DIR
    ALEXANDRIE_ENV_FILE="$APP_DIR/.env"
    ALEXANDRIE_COMPOSE_FILE="$APP_DIR/compose.yaml"
    export ALEXANDRIE_APP_DIR ALEXANDRIE_ENV_FILE ALEXANDRIE_COMPOSE_FILE
    # shellcheck disable=SC1091
    source "$LIB_DIR/lib.sh"
    load_env
    ip=$(hostname -I 2>/dev/null | awk '{print $1}')
    frontend=${FRONTEND_URL:-unconfigured}
    api=${API_URL:-unconfigured}
    cdn=${CDN_URL:-unconfigured}
    printf '\n=== Alexandrie ist installiert ===\n'
    printf 'LXC-IP:             %s\n' "${ip:-unbekannt}"
    printf 'Frontend lokal:     http://%s:8200\n' "${ip:-<LXC-IP>}"
    printf 'Backend lokal:       http://%s:8201\n' "${ip:-<LXC-IP>}"
    printf 'RustFS lokal:        http://%s:9000\n' "${ip:-<LXC-IP>}"
    printf 'Frontend öffentlich: %s\n' "$frontend"
    printf 'API öffentlich:      %s\n' "$api"
    printf 'CDN öffentlich:      %s\n' "$cdn"
    printf 'OIDC Redirect:       %s/login/oidc/callback\n' "$frontend"
    printf '\nVerwaltung: alexandrie-health, alexandrie-update, alexandrie-backup, alexandrie-config\n'
}

main() {
    require_root
    fail_if_existing_installation

    phase='network validation'
    check_network
    phase='base system update'
    apt-get update
    apt-get full-upgrade --yes
    apt-get install --yes ca-certificates curl gnupg jq openssl tar zstd lsb-release util-linux
    phase='Docker installation'
    install_docker
    phase='Alexandrie asset installation'
    download_assets
    phase='secret and configuration initialization'
    write_initial_environment
    phase='interactive OIDC configuration'
    alexandrie-config
    phase='Compose validation and image download'
    docker compose --project-name alexandrie --env-file "$APP_DIR/.env" --file "$APP_DIR/compose.yaml" config --quiet
    docker compose --project-name alexandrie --env-file "$APP_DIR/.env" --file "$APP_DIR/compose.yaml" pull
    phase='Alexandrie startup'
    docker compose --project-name alexandrie --env-file "$APP_DIR/.env" --file "$APP_DIR/compose.yaml" up -d --remove-orphans
    wait_for_stack || {
        printf '[ERROR] Stack wurde nicht innerhalb von 180 Sekunden gesund.\n' >&2
        docker compose --project-name alexandrie --env-file "$APP_DIR/.env" --file "$APP_DIR/compose.yaml" ps >&2 || true
        exit 1
    }
    phase='system integration'
    systemctl daemon-reload
    systemctl enable --now alexandrie.service
    touch "$APP_DIR/.installed"
    chown root:root "$APP_DIR/.installed"
    chmod 600 "$APP_DIR/.installed"
    if [[ -d /etc/update-motd.d ]]; then
        cat > /etc/update-motd.d/99-alexandrie <<'EOF'
#!/bin/sh
printf 'Alexandrie: alexandrie-health | alexandrie-update | alexandrie-backup\n'
EOF
        chmod 0755 /etc/update-motd.d/99-alexandrie
    fi
    print_summary
}

main "$@"
